### ISSUE TITLE
Can you create a node module for this library?

### ISSUE THREAD

**Issue by RTeran** [lmgonzalves/loading-buttons#1]

**Comment by lmgonzalves** [comment]
Hi, thanks for contributing!
The purpose of this repository is to provide examples to create good looking loading buttons. But it is not organized as a library.
Anyway, I've merged your pull request, hoping it can be useful for you and someone else.
Thanks again, and let me know if you need anything else :)

**Comment by RTeran** [comment]
I know this repo is only an example, but as simple as adding a package.json change allows the repo installed with NPM.

Thanks for all.
